from . import activities,\
              attendance,\
              core,\
              dashboard,\
              edupro,\
              enrolments,\
              enterprise,\
              fees,\
              health,\
              interviews,\
              markbook,\
              messaging,\
              plans,\
              portal,\
              reports,\
              restapi,\
              sentral,\
              staff,\
              timetables
